#ubuntu
version: "3.0"
services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /home/ec2-user/jenkins_data:/var/jenkins_hom
