version: '3.0'

services:

  nginx_cont:
    image: nginx
    ports:
      - "80:80"


  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretpass
    ports:
      - "3306:3306"
