version: '3.0'

services:

  nginx_container:
    image: nginx
    ports:
      - "8080:80"

    links:
      - database_container


  database_container:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secetpass
    ports:
      - "3000:3306"
